### ISSUE TITLE
Replace fyne.NewContainer... in favor of container.New...

### ISSUE THREAD

**Issue by fpabl0** [PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne#1]
- [ ]  https://github.com/PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne/blob/7aa442ad7959dcb6f280910c6a311b8c6e857c69/Chapter03/canvas/main.go#L27
- [ ] https://github.com/PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne/blob/7aa442ad7959dcb6f280910c6a311b8c6e857c69/Chapter03/example/main.go#L123
- [ ] https://github.com/PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne/blob/7aa442ad7959dcb6f280910c6a311b8c6e857c69/Chapter04/example/layout.go#L42
- [ ] https://github.com/PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne/blob/7aa442ad7959dcb6f280910c6a311b8c6e857c69/Chapter04/example/layout.go#L58
- [ ] https://github.com/PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne/blob/7aa442ad7959dcb6f280910c6a311b8c6e857c69/Chapter04/example/image.go#L92

**Comment by Jacalz** [comment]
Strange. These were all updated in the book.

cc @andydotxyz

**Comment by andydotxyz** [comment]
It seems that at least one (end of page 55) is not correct in the book content :(
