### ISSUE TITLE
On Linux, ./main.go:4:2: undefined: say

### ISSUE THREAD

**Issue by DaleEMoore** [PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne#2]
On Ubuntu 20.10 Linux with goLand 2021.1.1

```
$ go version
go version go1.16 linux/amd64
```
Compiling Chapter08/say/main.go gets

```
GOROOT=/usr/local/go #gosetup
GOPATH=/home/dalem/go #gosetup
/usr/local/go/bin/go build -o /tmp/___4go_build_main_go__1_ /home/dalem/GolandProjects/Building-Cross-Platform-GUI-Applications-with-Fyne/Chapter08/say/main.go #gosetup
&#35; command-line-arguments
./main.go:4:2: undefined: say

Compilation finished with exit code 

```
I suppose say_other.go's

`// +build !darwin`

is not taking effect.

**Comment by DaleEMoore** [comment]
That should have been:

`Compiling Chapter08/say/main.go gets`

**Comment by andydotxyz** [comment]
You don't share what command is used to build, I am guessing that you've used `go run main.go`.
Because there are multiple files you need to run `go run .` or `go run *.go` instead.

**Comment by shubham763** [comment]
If the issue still persists, please reopen.

**Comment by DaleEMoore** [comment]
Thanks @andydotxyz, I appreciate your feedback! I'm sorry it's taken me so long to address your response!! Here's what I'm getting now:

```
dalem@QnD7:~/GolandProjects/golang/src/class/Building-Cross-Platform-GUI-Applications-with-Fyne/Chapter08/say$ go run *.go
# command-line-arguments
./say_other.go:10:6: say redeclared in this block
        /home/dalem/GolandProjects/golang/src/class/Building-Cross-Platform-GUI-Applications-with-Fyne/Chapter08/say/say_darwin.go:8:15: previous declaration
```

**Comment by andydotxyz** [comment]
Hmm, the opposite problem. Very strange. Can you try `go run .` please?

**Comment by DaleEMoore** [comment]
Now I have a MUCH BETTER solution:

```
dalem@QnD7:~/GolandProjects/golang/src/class/Building-Cross-Platform-GUI-Applications-with-Fyne/Chapter08/say$ go run .
2021/10/28 09:21:22 Say support is not available for linux
```

Thanks for always being there!
Dale
