### ISSUE TITLE
Cross-Compiling: macOS (arm64) -> Windows (amd64) & Linux (amd64)

### ISSUE THREAD

**Issue by Klaus-Tockloth** [PacktPublishing/Building-Cross-Platform-GUI-Applications-with-Fyne#4]
Maybe helpful for others ... I'm using macOS 13.1 (Ventura) with Apple M1 Pro (arm64). 

-----

**macOS (arm64) -> Windows (amd64)**

_Page 282 Appendix C:Cross-Compiling
Installing Windows tools on macOS
...
$ CC= x86_64-w64-mingw64-gcc GOOS=windows CGO_ENABLED=1 go build ._

This works for me (after 'brew install' I have no binary 'x86_64-w64-mingw64-gcc'):
CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build .

-----

**macOS (arm64) -> Linux (amd64)**

_Page 283 Manually Installing compilers
Installing a Linux compiler on macOS
...
$ CC=x86_64-linux-musl-gcc GOOS=linux CGO_ENABLED=1 go build_
 
This works for me (LDFLAG added, tested with PKCS11-C-library not with Fyne):
CC=x86_64-linux-musl-cc GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build --ldflags '-extldflags "-static"' .

From https://github.com/FiloSottile/homebrew-musl-cross: The "musl" part of the target is important: the binaries will ONLY run on a musl-based system, like Alpine. However, if you build them as static binaries by passing -static as an LDFLAG they will run anywhere. Musl is specifically engineered to support static binaries.

-----

**Comment by andydotxyz** [comment]
Ah yes, thanks. When moving to M1 or M2 based Apple computers the default arch is no longer amd64, but arm64/aarch64 - so you have to add `GOARCH` parameters alongside `GOOS`.
Added a note in the README file.
